analysis:
  analyzer:
    name_suggest_index:
      tokenizer: edge_ngram_2
      filter:
      - lowercase
      - name_synonyms
      char_filter:
      - name_suggest
      - phonetic_mappings
    name_suggest_search:
      tokenizer: keyword
      filter:
      - lowercase
      - name_synonyms
      char_filter:
      - name_suggest
      - phonetic_mappings
    phone_number:
      tokenizer: keyword
      filter:
      - phone_number
      char_filter:
      - phone_number
  tokenizer:
    edge_ngram_2:
      type: edgeNGram
      min_gram: 2
      max_gram: 50
      token_chars:
      - letter
      - digit
  filter:
    phone_number:
      type: edgeNGram
      side: back
      min_gram: 5
      max_gram: 12
    name_synonyms:
      type: synonym
      synonyms:
      - "carl, karl"
      - "carlsson, karlsson"
      - "sophie, sofie"
      - "sophia, sofia"

  char_filter:
    phone_number:
      type: pattern_replace
      pattern: "[^0-9]"
      replacement: ''
    name_suggest:
      type: pattern_replace
      pattern: "[-,\\s]"
      replacement: ''
    phonetic_mappings:
      type: mapping
      mappings:
      - "y => ü"
